spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/class_design
    username: design
    password: design
  jpa:
    show-sql: true
  thymeleaf:
    cache: false
server:
  port: 8088
app:
  worker:
    id: 0
  data:
    center:
      id: 0